"""Increase password hash length

Revision ID: 330b6059b4b3
Revises: da11aceda5c3
Create Date: 2024-05-30 16:54:12.401524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '330b6059b4b3'
down_revision = 'da11aceda5c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
